apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: namespaces
  namespace: argocd # Namespace where Argo CD is installed
spec:
  project: default # The Argo CD Project this application belongs to
  source:
    repoURL: https://github.com/kvk55247/eks-argocd.git # URL of your Git repository
    targetRevision: main # The branch or commit hash to sync from
    path: namespaces # Path within the repository to your Kubernetes manifests
  destination:
    server: https://kubernetes.default.svc # The Kubernetes API server URL
    namespace: argocd # The namespace in the target cluster to deploy to
  syncPolicy:
    automated:
      prune: true # Automatically delete resources that are no longer in Git
      selfHeal: true # Automatically sync resources that drift from the desired state
    syncOptions:
      - CreateNamespace=true # Create the destination namespace if it doesn't exist